version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=test-database
    ports:
      - "27017-27019:27017-27019"
