version: '3'
services:
  cloudmesh:
    build: .
    volumes:
      - .:/code
      - ~/.cloudmesh:/root/.cloudmesh
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <your-username>
      MONGO_INITDB_ROOT_PASSWORD: <your-password>
      MONGO_INITDB_DATABASE: cloudmesh
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
